version: '3.2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      - DEFAULT_EMAIL=admin@acetousk.com
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - db
    expose:
      - "9000"
    ports:
      - "9000:80"
    environment:
      - LETSENCRYPT_HOST=cloud.dmichaeljones.com
      - VIRTUAL_HOST=cloud.dmichaeljones.com
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=https
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    volumes:
      - ./nextcloud:/var/www/html
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user


  redis:
    image: redis:alpine
    restart: always

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
  nextcloud:
  db:
#  nextcloud_aio_mastercontainer:
#    name: nextcloud_aio_mastercontainer

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt # put admin password in this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt # put admin username in this file
  postgres_db:
    file: ./postgres_db.txt # put postgresql db name in this file
  postgres_password:
    file: ./postgres_password.txt # put postgresql password in this file
  postgres_user:
    file: ./postgres_user.txt # put postgresql username in this file

#  nextcloud:
#    image: nextcloud/all-in-one:latest
#    restart: unless-stopped
#    container_name: nextcloud-aio-mastercontainer
#    expose:
#      - "8080"
#    ports:
#      - "8080:8080"
#    environment:
#      - APACHE_PORT=11000
#      - LETSENCRYPT_HOST=aio.cloud.dmichaeljones.com
#      - VIRTUAL_HOST=aio.cloud.dmichaeljones.com
#      - VIRTUAL_PORT=8080
#      - VIRTUAL_PROTO=https
#    volumes:
#      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
#      - /var/run/docker.sock:/var/run/docker.sock:ro

